######################################################################
#
# File name : decoder_tb_simulate.do
# Created on: Mon Oct 16 20:05:58 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.decoder_tb xil_defaultlib.glbl

do {decoder_tb_wave.do}

view wave
view structure
view signals

do {decoder_tb.udo}

run 1000ns
