######################################################################
#
# File name : pcreg_tb_wave.do
# Created on: Mon Nov 06 21:08:57 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
