######################################################################
#
# File name : pcreg_tb_compile.do
# Created on: Mon Nov 06 21:08:49 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib work
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../6.6_4.srcs/sources_1/new/pcreg.v" \
"../../../6.6_4.srcs/sources_1/new/pcreg_tb.v" \


# compile glbl module
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

