######################################################################
#
# File name : Synchronous_D_FF_tb_wave.do
# Created on: Mon Nov 06 19:31:56 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
