######################################################################
#
# File name : DataCompare4_tb.udo
# Created on: Mon Oct 30 19:29:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
