######################################################################
#
# File name : DataCompare4_tb_compile.do
# Created on: Mon Oct 30 19:32:54 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib work
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../6.5_1.srcs/sources_1/new/DataCompare4.v" \
"../../../6.5_1.srcs/sources_1/new/DataCompare4_tb.v" \


# compile glbl module
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

