######################################################################
#
# File name : DataCompare4_tb_wave.do
# Created on: Mon Oct 30 19:33:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
