######################################################################
#
# File name : DataCompare8_tb_wave.do
# Created on: Mon Oct 30 20:02:21 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
