######################################################################
#
# File name : selector41_tb_wave.do
# Created on: Mon Oct 09 21:28:18 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
