######################################################################
#
# File name : selector41_tb_simulate.do
# Created on: Mon Oct 09 21:28:18 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.selector41_tb xil_defaultlib.glbl

do {selector41_tb_wave.do}

view wave
view structure
view signals

do {selector41_tb.udo}

run 1000ns
