######################################################################
#
# File name : Adder_tb_simulate.do
# Created on: Mon Oct 30 20:50:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.Adder_tb xil_defaultlib.glbl

do {Adder_tb_wave.do}

view wave
view structure
view signals

do {Adder_tb.udo}

run 1000ns
