######################################################################
#
# File name : three_state_gates_tb_compile.do
# Created on: Mon Sep 25 21:35:45 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib work
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../6.1_4.srcs/sources_1/new/three_state_gates.v" \
"../../../6.1_4.srcs/sources_1/new/three_state_gates_tb.v" \


# compile glbl module
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

