######################################################################
#
# File name : three_state_gates_tb.udo
# Created on: Mon Sep 25 21:35:53 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
