######################################################################
#
# File name : three_state_gates_tb_wave.do
# Created on: Mon Sep 25 21:35:53 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
