######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Mon Sep 25 20:35:55 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
