######################################################################
#
# File name : JK_FF_tb_wave.do
# Created on: Mon Nov 06 20:31:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
