######################################################################
#
# File name : JK_FF_tb.udo
# Created on: Mon Nov 06 20:29:48 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
