######################################################################
#
# File name : encoder83_pri_tb_wave.do
# Created on: Mon Oct 16 23:24:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
