######################################################################
#
# File name : encoder83_pri_tb_simulate.do
# Created on: Mon Oct 16 23:24:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.encoder83_pri_tb xil_defaultlib.glbl

do {encoder83_pri_tb_wave.do}

view wave
view structure
view signals

do {encoder83_pri_tb.udo}

run 1000ns
