######################################################################
#
# File name : encoder83_pri_tb.udo
# Created on: Mon Oct 16 23:15:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
