
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.3 EDK_P.40xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemaclite.h"

/*
* The configuration table for devices
*/

XEmacLite_Config XEmacLite_ConfigTable[] =
{
	{
		XPAR_GENERIC_ETHERNET_10_100_DEVICE_ID,
		XPAR_GENERIC_ETHERNET_10_100_BASEADDR,
		XPAR_GENERIC_ETHERNET_10_100_TX_PING_PONG,
		XPAR_GENERIC_ETHERNET_10_100_RX_PING_PONG,
		XPAR_GENERIC_ETHERNET_10_100_INCLUDE_MDIO,
		XPAR_GENERIC_ETHERNET_10_100_INCLUDE_INTERNAL_LOOPBACK
	}
};


