######################################################################
#
# File name : encoder83_tb.udo
# Created on: Mon Oct 16 22:13:17 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
