######################################################################
#
# File name : encoder83_tb_wave.do
# Created on: Mon Oct 16 22:14:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
