#ChipScope Core Inserter Project File Version 3.0
#Mon Nov 25 13:49:49 CST 2013
Project.device.designInputFile=D\:\\hc_work\\New_product\\Nexys4\\ps2_test\\top_cs.ngc
Project.device.designOutputFile=D\:\\hc_work\\New_product\\Nexys4\\ps2_test\\top_cs.ngc
Project.device.deviceFamily=21
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\hc_work\\New_product\\Nexys4\\ps2_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=1
Project.filter<0>=
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=clk_50M
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=KClk_IBUF
Project.unit<0>.dataChannel<10>=Inst_Ps2Receiver key_code<7>
Project.unit<0>.dataChannel<11>=Inst_Ps2Receiver key_code<6>
Project.unit<0>.dataChannel<12>=Inst_Ps2Receiver key_code<5>
Project.unit<0>.dataChannel<13>=Inst_Ps2Receiver key_code<4>
Project.unit<0>.dataChannel<14>=Inst_Ps2Receiver key_code<3>
Project.unit<0>.dataChannel<15>=Inst_Ps2Receiver key_code<2>
Project.unit<0>.dataChannel<16>=Inst_Ps2Receiver key_code<1>
Project.unit<0>.dataChannel<17>=Inst_Ps2Receiver key_code<0>
Project.unit<0>.dataChannel<18>=Inst_Ps2Receiver par
Project.unit<0>.dataChannel<19>=Inst_Ps2Receiver wdg
Project.unit<0>.dataChannel<1>=KData_IBUF
Project.unit<0>.dataChannel<2>=Inst_Ps2Receiver key_code<15>
Project.unit<0>.dataChannel<3>=Inst_Ps2Receiver key_code<14>
Project.unit<0>.dataChannel<4>=Inst_Ps2Receiver key_code<13>
Project.unit<0>.dataChannel<5>=Inst_Ps2Receiver key_code<12>
Project.unit<0>.dataChannel<6>=Inst_Ps2Receiver key_code<11>
Project.unit<0>.dataChannel<7>=Inst_Ps2Receiver key_code<10>
Project.unit<0>.dataChannel<8>=Inst_Ps2Receiver key_code<9>
Project.unit<0>.dataChannel<9>=Inst_Ps2Receiver key_code<8>
Project.unit<0>.dataDepth=131072
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=20
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=KClk_IBUF
Project.unit<0>.triggerChannel<0><10>=
Project.unit<0>.triggerChannel<0><11>=
Project.unit<0>.triggerChannel<0><12>=
Project.unit<0>.triggerChannel<0><13>=
Project.unit<0>.triggerChannel<0><14>=
Project.unit<0>.triggerChannel<0><15>=
Project.unit<0>.triggerChannel<0><16>=
Project.unit<0>.triggerChannel<0><17>=
Project.unit<0>.triggerChannel<0><18>=
Project.unit<0>.triggerChannel<0><19>=
Project.unit<0>.triggerChannel<0><1>=KData_IBUF
Project.unit<0>.triggerChannel<0><2>=Inst_Ps2Receiver par
Project.unit<0>.triggerChannel<0><3>=Inst_Ps2Receiver wdg
Project.unit<0>.triggerChannel<0><4>=
Project.unit<0>.triggerChannel<0><5>=
Project.unit<0>.triggerChannel<0><6>=
Project.unit<0>.triggerChannel<0><7>=
Project.unit<0>.triggerChannel<0><8>=
Project.unit<0>.triggerChannel<0><9>=
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=4
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
