######################################################################
#
# File name : ram_tb_wave.do
# Created on: Mon Nov 27 23:29:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
