######################################################################
#
# File name : ram_tb.udo
# Created on: Mon Nov 27 18:15:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
