######################################################################
#
# File name : Regfiles_tb_simulate.do
# Created on: Tue Nov 28 13:02:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.Regfiles_tb xil_defaultlib.glbl

do {Regfiles_tb_wave.do}

view wave
view structure
view signals

do {Regfiles_tb.udo}

run 1000ns
