######################################################################
#
# File name : Regfiles_tb_wave.do
# Created on: Tue Nov 28 13:02:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
