######################################################################
#
# File name : logic_gates_3.udo
# Created on: Mon Sep 25 21:07:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
