######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Mon Sep 25 22:50:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
