######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Mon Sep 25 22:50:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
