######################################################################
#
# File name : extend_tb_wave.do
# Created on: Mon Sep 25 23:16:47 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
