######################################################################
#
# File name : barrelshifter32_tb_wave.do
# Created on: Mon Oct 23 20:55:47 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
