# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath E:/szlj/modelsim_dlx_10.3a/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/szlj/vivado_save/bigwork/bigwork.cache/wt [current_project]
set_property parent.project_path E:/szlj/vivado_save/bigwork/bigwork.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files E:/szlj/vivado_save/bigwork/MP3/Wings_of_Piano_hex.COE
add_files E:/szlj/vivado_save/bigwork/MP3/PaperPlane_hex.COE
add_files E:/szlj/vivado_save/bigwork/MP3/Pure_32_hex.COE
add_files E:/szlj/vivado_save/bigwork/MP3/Grievous_Lady_hex.COE
add_files E:/szlj/vivado_save/bigwork/MP3/Tempestissimo_hex.COE
add_files E:/szlj/vivado_save/bigwork/MP3/merry_christmas.coe
add_files -quiet e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
add_files -quiet e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
add_files -quiet e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp
set_property used_in_implementation false [get_files e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp]
add_files -quiet e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.dcp
set_property used_in_implementation false [get_files e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.dcp]
add_files -quiet e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.dcp
set_property used_in_implementation false [get_files e:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.dcp]
read_verilog -library xil_defaultlib {
  E:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/new/tetris_control.v
  E:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/new/VGA.v
  E:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/new/Divider.v
  E:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/new/display_score.v
  E:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/new/MP3.v
  E:/szlj/vivado_save/bigwork/bigwork.srcs/sources_1/new/bigwork_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/szlj/vivado_save/bigwork/bigwork.srcs/constrs_1/new/bigwork_top.xdc
set_property used_in_implementation false [get_files E:/szlj/vivado_save/bigwork/bigwork.srcs/constrs_1/new/bigwork_top.xdc]


synth_design -top GAME_TOP -part xc7a100tcsg324-1


write_checkpoint -force -noxdef GAME_TOP.dcp

catch { report_utilization -file GAME_TOP_utilization_synth.rpt -pb GAME_TOP_utilization_synth.pb }
