######################################################################
#
# File name : ALU_tb_simulate.do
# Created on: Tue Nov 21 08:47:37 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.ALU_tb xil_defaultlib.glbl

do {ALU_tb_wave.do}

view wave
view structure
view signals

do {ALU_tb.udo}

run 1000ns
