######################################################################
#
# File name : ALU_tb_wave.do
# Created on: Tue Nov 21 08:47:37 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
