######################################################################
#
# File name : ram2_tb_compile.do
# Created on: Mon Nov 27 23:39:31 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib work
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../ram2.v" \
"../../../ram2_tb.v" \


# compile glbl module
E:\\szlj\\modelsim_dlx_10.3a\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

