######################################################################
#
# File name : ram2_tb.udo
# Created on: Mon Nov 27 19:09:50 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
